unique_name: adventurer
display_name: $almanac_achievement_adventurer
sprite_name: BlackCore
description: $almanac_achievement_adventurer_desc
lore: $almanac_adventurer_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_poison</color>

  $almanac_increase_stamina_regen_by <color=orange>50</color>%
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
- vfx_HealthUpgrade
stop_effects: 
achievement_type: TimeOutOfBase
goal: 50000
resistance_modifier: Poison = Weak
modifier: StaminaRegen
modifier_value: 1.5
activation_animation: gpower
cooldown: 0
defeat_key: ''
