unique_name: brew_master
display_name: $almanac_achievement_brew_master
sprite_name: almanac_bottle_blue
description: $almanac_achievement_brew_master_desc
lore: $almanac_brew_master_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_frost</color>

  $almanac_increase_fire_damage_by <color=orange>5</color>
stop_message: $almanac_damage_default
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: Potions
goal: 0
resistance_modifier: Frost = Weak
modifier: FireDMG
modifier_value: 5
activation_animation: gpower
cooldown: 0
defeat_key: ''
