unique_name: cultist_hunter
display_name: $almanac_achievement_cultist_hunter
sprite_name: almanac_book_red
description: $almanac_achievement_cultist_hunter_desc
lore: $almanac_cultist_hunter_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_frost</color>

  $almanac_increase_fire_damage_by <color=orange>5</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: CultistKills
goal: 100
resistance_modifier: Frost = Weak
modifier: FireDMG
modifier_value: 5
activation_animation: gpower
cooldown: 0
defeat_key: ''
