unique_name: daredevil
display_name: $almanac_achievement_daredevil
sprite_name: YagluthDrop
description: $almanac_achievement_daredevil_desc
lore: $almanac_daredevil_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_spirit</color>

  $almanac_increase_stamina_by <color=orange>5</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: DeathByEdge
goal: 1
resistance_modifier: Spirit = Weak
modifier: BaseStamina
modifier_value: 5
activation_animation: gpower
cooldown: 0
defeat_key: ''
