unique_name: fenring
display_name: $almanac_achievement_fenring
sprite_name: TrophyUlv
description: $almanac_achievement_fenring_desc
lore: $almanac_fenring_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_spirit</color>

  $almanac_increase_spirit_damage_by <color=orange>5</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: FenringKills
goal: 100
resistance_modifier: Spirit = Weak
modifier: SpiritDMG
modifier_value: 5
activation_animation: gpower
cooldown: 0
defeat_key: ''
