unique_name: fisher
display_name: $almanac_achievement_fisher
sprite_name: almanac_fish_green
description: $almanac_achievement_fisher_desc
lore: $almanac_fisher_lore
tool_tip: $almanac_allows_moder_power
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: Fish
goal: 0
resistance_modifier: ''
modifier: ModerPower
modifier_value: 0
activation_animation: gpower
cooldown: 0
defeat_key: ''
