unique_name: gaseous
display_name: $almanac_achievement_gaseous
sprite_name: BombOoze
description: $almanac_achievement_gaseous_desc
lore: $almanac_gaseous_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_poison</color>

  $almanac_increase_poison_damage_by <color=orange>5</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: TotalKills
goal: 500
resistance_modifier: Poison = Weak
modifier: PoisonDMG
modifier_value: 5
activation_animation: gpower
cooldown: 0
defeat_key: ''
