unique_name: gluttony
display_name: $almanac_achievement_gluttony
sprite_name: almanac_mushroom
description: $almanac_achievement_gluttony_desc
lore: $almanac_gluttony_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_very_resistant</color> VS <color=orange>$almanac_poison</color>

  $almanac_reduce_health_by <color=orange>5</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: Consumables
goal: 0
resistance_modifier: Poison = VeryResistant
modifier: BaseHP
modifier_value: -5
activation_animation: gpower
cooldown: 0
defeat_key: ''
