unique_name: killer
display_name: $almanac_achievement_killer
sprite_name: Acorn
description: $almanac_achievement_killer_desc
lore: $almanac_killer_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_fire</color>

  $almanac_increase_attack_by <color=orange>50</color>%
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: TotalKills
goal: 100000
resistance_modifier: Fire = Weak
modifier: Attack
modifier_value: 1.5
activation_animation: gpower
cooldown: 0
defeat_key: ''
