unique_name: lumberjack
display_name: $almanac_achievement_lumberjack
sprite_name: almanac_wood_stack
description: $almanac_achievement_lumberjack_desc
lore: $almanac_lumberjack_lore
tool_tip: $almanac_increase_chop_damage_by <color=orange>10</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: Trees
goal: 1000
resistance_modifier: ''
modifier: ChopDMG
modifier_value: 10
activation_animation: gpower
cooldown: 0
defeat_key: ''
