unique_name: turret
display_name: $almanac_achievement_turret
sprite_name: ArrowCarapace
description: $almanac_achievement_turret_desc
lore: $almanac_turret_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_fire</color>

  $almanac_increase_projectile_damage_by <color=orange>5</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: ArrowsShot
goal: 1000
resistance_modifier: Fire = Weak
modifier: RangedDMG
modifier_value: 5
activation_animation: gpower
cooldown: 0
defeat_key: ''
