unique_name: undying
display_name: $almanac_achievement_undying
sprite_name: almanac_bone_skull
description: $almanac_achievement_undying_desc
lore: $almanac_undying_lore
tool_tip: >-
  $almanac_modify_damage_by <color=orange>$almanac_weak</color> VS <color=orange>$almanac_spirit</color>

  $almanac_increase_stamina_by <color=orange>10</color>
stop_message: $almanac_removed_achievement_power
start_effects:
- sfx_coins_placed
stop_effects: 
achievement_type: Deaths
goal: 200
resistance_modifier: Spirit = Weak
modifier: BaseStamina
modifier_value: 10
activation_animation: gpower
cooldown: 0
defeat_key: ''
