BossHildir1: 0
BossHildir2: 0
defeated_goblinbrute_hildir: 0
BossHildir3: 0
defeated_goblinshaman_hildir: 0
defeated_goblinshaman_hildir_nochest: 0
defeated_abomination: 0
defeated_krump_monster_neck: 0
KilledBat: 0
defeated_krump_monsters_swamp_blob: 0
defeated_blob: 0
defeated_boar: 0
defeated_krump_monsters_blackforest_boarlet: 0
defeated_bonemass: 0
defeated_leech_cave: 0
defeated_d_chicken: 0
defeated_chicken: 0
defeated_krump_monsters_blackforest_rat_01: 0
defeated_fenring_cultist: 0
defeated_deathsquito: 0
defeated_deer: 0
defeated_krump_monsters_meadows_deer_doe: 0
defeated_hatchling: 0
defeated_krump_monsters_swamp_draugr1: 0
defeated_krump_monsters_swamp_draugr0: 0
defeated_draugr: 0
defeated_draugr_elite: 0
defeated_krump_monsters_swamp_draugrelite_01: 0
defeated_krump_monsters_swamp_draugrking: 0
defeated_dvergermage: 0
defeated_dverger: 0
defeated_eikthyr: 0
defeated_krump_monsters_blackforest_shadow: 0
defeated_krump_monsters_meadows_deer_fawn: 0
defeated_fenring: 0
defeated_dvergermagefire: 0
defeated_goblin: 0
defeated_goblinbrute: 0
defeated_goblinshaman: 0
defeated_ghost: 0
defeated_krump_monster_neck_brute: 0
defeated_krump_monsters_plains_giantsandworm0: 0
defeated_gjall: 0
defeated_krump_monsters_meadows_greydwarf_f: 0
defeated_krump_monsters_meadows_greydwarf_m: 0
defeated_greydwarf: 0
defeated_greydwarf_elite: 0
defeated_krump_monsters_meadows_greydwarf_brute: 0
defeated_greydwarf_shaman: 0
defeated_krump_monsters_meadows_greydwarf_shaman: 0
defeated_greyling: 0
defeated_krump_monsters_meadows_greyling_m: 0
defeated_krump_monsters_meadows_greyling_f: 0
defeated_blobtar: 0
defeated_hare: 0
defeated_d_hen: 0
defeated_hen: 0
defeated_krump_monsters_blackforest_warboar_boss: 0
defeated_dvergermageice: 0
defeated_krump_monsters_meadows_lamb: 0
defeated_krump_monsters_blackforest_rat_02: 59
defeated_leech: 0
defeated_lox: 0
defeated_lox_calf: 0
defeated_mistile: 0
defeated_dragon: 0
defeated_neck: 0
$Killed_Boss_Nokken: 0
defeated_blobelite: 0
defeated_krump_monsters_meadows_pig: 0
defeated_krump_monsters_meadows_pig_male: 0
defeated_boar_piggy: 0
defeated_krump_monsters_meadows_piglet: 0
defeated_krump_monsters_meadows_ram: 0
defeated_skeleton_poison: 0
defeated_draugr_ranged: 0
defeated_goblinarcher: 0
defeated_krump_monsters_blackforest_rat_small_01: 0
defeated_krump_monsters_tentaroot: 0
defeated_tentaroot: 0
defeated_krump_monsters_plains_sandworm0: 0
defeated_seeker: 0
defeated_seekerbrood: 0
defeated_seekerbrute: 0
defeated_serpent: 0
defeated_krump_monsters_meadows_sheep: 0
defeated_krump_monsters_blackforest_skeleton: 0
defeated_krump_monsters_swamp_skeleton: 0
defeated_skeleton: 0
defeated_skeleton_noarcher: 0
defeated_skeleton_friendly: 0
defeated_krump_monsters_meadows_deer_stag: 0
defeated_stonegolem: 0
defeated_dvergermagesupport: 0
killed_surtling: 0
defeated_gdking: 1
defeated_queen: 0
defeated_tick: 0
defeated_krump_monsters_blackforest_troll_01: 0
KilledTroll: 0
defeated_ulv: 0
defeated_krump_monsters_npc_male1: 0
defeated_krump_monsters_npc_male2: 0
defeated_krump_monsters_npc_male3: 0
defeated_krump_monsters_npc_male0: 0
defeated_krump_monsters_npc_random: 0
defeated_krump_monsters_blackforest_wearrat_01: 0
defeated_krump_monsters_blackforest_boar_male: 0
defeated_krump_monsters_blackforest_boar_female: 0
defeated_wolf: 0
defeated_wolf_cub: 0
defeated_wraith: 0
defeated_goblinking: 0
defeated_krump_monsters_meadows_giantneck: 0
defeated_krump_monsters_npc_male4: 0
defeated_krump_monsters_meadows_angryneck: 0
