#List out creature prefabs to blacklist:
#general list to ignore
Player
TentaRoot
TheHive
TrainingDummy
Hive
Mistile
#Replaced Meadows
Boar
Boar_piggy
Chicken
Deer
Greyling
#Replaced Forest
Troll
Greydwarf
Greydwarf_Elite
Greydwarf_Shaman
#Replaced Swamp
Draugr
Draugr_Elite
Draugr_Ranged
#Cats
Cat1_Kitten
Cat2_Kitten
Cat3_Kitten
Cat4_Kitten
Cat5_Kitten
Cat6_Kitten
Cat7_Kitten
Cat8_Kitten
Cat9_Kitten
Cat10_Kitten
Cat11_Kitten
KittenHappyBox