---
# List out items prefabs to ignore:

StaminaUpgrade_Greydwarf
StaminaUpgrade_Troll
StaminaUpgrade_Wraith
IronOre
DvergerArbalest_shoot
DvergerArbalest
CapeTest
SledgeCheat
SwordCheat
HealthUpgrade_Bonemass
HealthUpgrade_GDKing
guard_stone_test
Trailership
TorchMist
NPC_HelmetIron_Worn0
NPC_HelmetBronze_Worn0
NPC_ArmorIronChest_Worn
NPC_ArmorIronLegs_Worn
VegvisirShard_Bonemass
Cat1_Kitten
Cat2_Kitten
Cat3_Kitten
Cat4_Kitten
Cat5_Kitten
Cat6_Kitten
Cat7_Kitten
Cat8_Kitten
Cat9_Kitten
Cat10_Kitten
Cat11_Kitten
KittenHappyBox

Krump_Vanilla_Replaced

Fish1
Fish2
Fish3
Fish4_cave
Fish5
Fish6
Fish7
Fish8
Fish9
Fish10
Fish11
Fish12

ArrowBronze
ArrowCarapace
ArrowFire
ArrowFlint
ArrowFrost
ArrowIron
ArrowNeedle
ArrowObsidian
ArrowPoison
ArrowSilver
ArrowWood
BoltBlackmetal
BoltBone
BoltCarapace
BoltIron
FishingBait
FishingBaitAshlands
FishingBaitCave
FishingBaitDeepNorth
FishingBaitForest
FishingBaitMistlands
FishingBaitOcean
FishingBaitPlains
FishingBaitSwamp
D_Song1
TurretBolt
TurretBoltWood

AxeJotunBane
BombBile
MaceNeedle
PlayerUnarmed
SpearCarapace
SpearElderbark
SwordIron
SwordMistwalker
Tankard
Tankard_dvergr
TankardAnniversary
TankardOdin
Club
BowSpineSnap
CrossbowArbalest
ShieldCarapace
ShieldCarapaceBuckler
ShieldWoodTower
AtgeirHimminAfl
KnifeSkollAndHati
PickaxeBlackMetal
PickaxeBronze
PickaxeIron
PickaxeStone
SledgeDemolisher
StaffFireball
StaffIceShards
StaffShield
THSwordKrom
Lantern
Sparkler
Cultivator
Hoe
StaffSkeleton

BarberKit
ArmorDress6
ArmorDress3
ArmorDress9
ArmorTunic3
ArmorTunic6
ArmorTunic9
CapeOdin
ArmorTunic2
ArmorTunic5
ArmorTunic8
ArmorCarapaceChest
ArmorCarapaceLegs
HelmetCarapace
CapeDeerHide
HelmetDrake
HelmetDraugr0
HelmetDraugr1
HelmetDraugr2
HelmetDraugr3
TrophyDraugrElite
TrophyDraugr
HelmetDverger
HelmetMage
ArmorMageChest
ArmorMageLegs
HelmetHat4
HelmetHat9
CapeFeather
TrophyDraugrFem
HelmetFishingHat
HelmetHat3
HelmetHat8
HelmetOdin
CapeLinen
CapeLox
SaddleLox
BeltStrength
HelmetMidsummerCrown
Krump_Armor_NPC_Chest_01
Krump_Armor_NPC_Chest_02
Krump_Armor_NPC_Chest_03
Krump_Armor_NPC_Helmet_02
Krump_Armor_NPC_Helmet_03
Krump_Armor_NPC_Helmet_04
Krump_Armor_NPC_Helmet_05
DraugrKing_Mace_2Hand
HelmetPadded
HelmetPointyHat
Krump_Armor_Druid_Chest_03
Krump_Armor_Druid_Chest_02
Krump_Armor_Druid_Chest_01
ArmorDress5
ArmorDress2
ArmorDress8
HelmetHat10
HelmetHat5
ArmorDress4
ArmorDress1
ArmorDress10
ArmorDress7
ArmorTunic1
ArmorTunic10
ArmorTunic4
ArmorTunic7
HelmetHat1
HelmetHat6
CapeTrollHide
TrophyFrostTroll
HelmetHat2
HelmetHat7
Demister
ArmorWolfChest
ArmorWolfLegs
CapeWolf
HelmetYule

ArmorBronzeChest
ArmorBronzeLegs
ArmorFenringChest
ArmorFenringLegs
ArmorIronChest
ArmorIronLegs
ArmorLeatherChest
ArmorLeatherLegs
ArmorPaddedCuirass
ArmorPaddedGreaves
ArmorRagsChest
ArmorRagsLegs
ArmorRootChest
ArmorRootLegs
ArmorTrollLeatherChest
ArmorTrollLeatherLegs
AtgeirBlackmetal
AtgeirBronze
AtgeirIron
AxeBlackMetal
AxeBronze
AxeFlint
AxeIron
AxeStone
BarleyWine
Battleaxe
BattleaxeCrystal
BlackSoup
BloodPudding
Blueberries
BoarJerky
Bow
BowDraugrFang
BowFineWood
BowHuntsman
Bread
Carrot
CarrotSoup
Cloudberry
CookedBugMeat
CookedChickenMeat
CookedDeerMeat
CookedEgg
CookedHareMeat
CookedLoxMeat
CookedMeat
CookedWolfMeat
DeerStew
Eyescream
FishAndBread
FishCooked
FishingRod
FishWraps
FistFenrirClaw
HelmetBronze
HelmetFenring
HelmetIron
HelmetLeather
HelmetRoot
HelmetTrollLeather
HoneyGlazedChicken
KnifeBlackMetal
KnifeButcher
KnifeChitin
KnifeCopper
KnifeFlint
KnifeSilver
LoxPie
MaceBronze
MaceIron
MaceSilver
MagicallyStuffedShroom
MeadEitrMinor
MeadFrostResist
MeadHealthMajor
MeadHealthMedium
MeadHealthMinor
MeadPoisonResist
MeadStaminaLingering
MeadStaminaMedium
MeadStaminaMinor
MeadTasty
MeatPlatter
MinceMeatSauce
MisthareSupreme
Mushroom
MushroomBlue
MushroomJotunPuffs
MushroomMagecap
MushroomOmelette
MushroomYellow
NeckTailGrilled
Onion
OnionSoup
PickaxeAntler
QueensJam
Raspberry
RottenMeat
RoyalJelly
Salad
Sausages
SeekerAspic
SerpentMeatCooked
SerpentStew
ShieldBanded
ShieldBlackmetal
ShieldBlackmetalTower
ShieldBoneTower
ShieldBronzeBuckler
ShieldIronBuckler
ShieldIronSquare
ShieldIronTower
ShieldKnight
ShieldSerpentscale
ShieldSilver
ShieldWood
ShocklateSmoothie
SledgeCheat
SledgeIron
SledgeStagbreaker
SpearBronze
SpearChitin
SpearFlint
SpearWolfFang
SwordBlackmetal
SwordBronze
SwordIronFire
SwordSilver
Turnip
TurnipStew
WolfJerky
WolfMeatSkewer
YggdrasilPorridge
ct_campfireinabottle
ct_bonfireinabottle
ct_livingroominabottle

Acorn
Barley
BarleyFlour
BarleyWineBase
Bilebag
BeechSeeds
BirchSeeds
BlackCore
BlackMarble
BlackMetal
BlackMetalScrap
BoneFragments
BreadDough
Bronze
BronzeNails
BronzeScrap
BugMeat
Carapace
CarrotSeeds
ChickenMeat
Chitin
Coal
Copper
CopperOre
CopperScrap
Crystal
Dandelion
DeerHide
DeerMeat
DragonTear
DvergrKeyFragment
DvergrNeedle
Eitr
ElderBark
Entrails
Feathers
FineWood
FirCone
FireworksRocket_Blue
FireworksRocket_Cyan
FireworksRocket_Green
FireworksRocket_Purple
FireworksRocket_Red
FireworksRocket_White
FireworksRocket_Yellow
FishAndBreadUncooked
FishAnglerRaw
FishRaw
Flametal
FlametalOre
Flax
Flint
FreezeGland
GiantBloodSack
Guck
HardAntler
HareMeat
Honey
HoneyGlazedChickenUncooked
Iron
IronNails
Ironpit
IronScrap
JuteBlue
JuteRed
Larva
LeatherScraps
LinenThread
LoxMeat
LoxPieUncooked
MagicallyStuffedShroomUncooked
Mandible
MeadBaseEitrMinor
MeadBaseFrostResist
MeadBaseHealthMajor
MeadBaseHealthMedium
MeadBaseHealthMinor
MeadBasePoisonResist
MeadBaseStaminaLingering
MeadBaseStaminaMedium
MeadBaseStaminaMinor
MeadBaseTasty
MeatPlatterUncooked
MechanicalSpring
MisthareSupremeUncooked
NeckTail
Needle
Obsidian
OnionSeeds
PineCone
QueenDrop
RawMeat
Resin
Root
RoundLog
Sap
ScaleHide
SerpentScale
SharpeningStone
Silver
SilverOre
Softtissue
Stone
Tar
Thistle
Thunderstone
Tin
TinOre
Torch
TrollHide
TurnipSeeds
Wisp
WolfClaw
WolfFang
WolfHairBundle
WolfMeat
WolfPelt
YagluthDrop
YggdrasilWood
YmirRemains
chest_hildir1
chest_hildir2
chest_hildir3
ChickenEgg
CryptKey
DvergrKey
HildirKey_forestcrypt
HildirKey_mountaincave
HildirKey_plainsfortress

Skeleton_Hildir
Skeleton_Hildir_nochest
Fenring_Cultist_Hildir
Fenring_Cultist_Hildir_nochest
GoblinBrute_Hildir
GoblinBruteBros
GoblinBruteBros_nochest
GoblinShaman_Hildir
GoblinShaman_Hildir_nochest

TBD


Player
TentaRoot
TheHive
TrainingDummy
Hive
Mistile
Boar
Boar_piggy
Chicken
Deer
Greyling
Troll
Greydwarf
Greydwarf_Elite
Greydwarf_Shaman
Draugr
Draugr_Elite
Draugr_Ranged
Blob
BlobElite


