---
# List out items prefabs to ignore:

StaminaUpgrade_Greydwarf
StaminaUpgrade_Troll
StaminaUpgrade_Wraith
IronOre
DvergerArbalest_shoot
DvergerArbalest
CapeTest
SledgeCheat
SwordCheat
HealthUpgrade_Bonemass
HealthUpgrade_GDKing
guard_stone_test
Trailership
TorchMist
NPC_HelmetIron_Worn0
NPC_HelmetBronze_Worn0
NPC_ArmorIronChest_Worn
NPC_ArmorIronLegs_Worn
VegvisirShard_Bonemass
Cat1_Kitten
Cat2_Kitten
Cat3_Kitten
Cat4_Kitten
Cat5_Kitten
Cat6_Kitten
Cat7_Kitten
Cat8_Kitten
Cat9_Kitten
Cat10_Kitten
Cat11_Kitten
KittenHappyBox

Krump_Vanilla_Replaced

Fish1
Fish2
Fish3
Fish4_cave
Fish5
Fish6
Fish7
Fish8
Fish9
Fish10
Fish11
Fish12

ArrowBronze
ArrowCarapace
ArrowFire
ArrowFlint
ArrowFrost
ArrowIron
ArrowNeedle
ArrowObsidian
ArrowPoison
ArrowSilver
ArrowWood
BoltBlackmetal
BoltBone
BoltCarapace
BoltIron
FishingBait
FishingBaitAshlands
FishingBaitCave
FishingBaitDeepNorth
FishingBaitForest
FishingBaitMistlands
FishingBaitOcean
FishingBaitPlains
FishingBaitSwamp
D_Song1
TurretBolt
TurretBoltWood

AxeJotunBane
BombBile
MaceNeedle
PlayerUnarmed
SpearCarapace
SpearElderbark
SwordIron
SwordMistwalker
Tankard
Tankard_dvergr
TankardAnniversary
TankardOdin
Club
BowSpineSnap
CrossbowArbalest
ShieldCarapace
ShieldCarapaceBuckler
ShieldWoodTower
AtgeirHimminAfl
KnifeSkollAndHati
PickaxeBlackMetal
PickaxeBronze
PickaxeIron
PickaxeStone
SledgeDemolisher
StaffFireball
StaffIceShards
StaffShield
THSwordKrom
Lantern
Sparkler
Cultivator
Hoe
StaffSkeleton

BarberKit
ArmorDress6
ArmorDress3
ArmorDress9
ArmorTunic3
ArmorTunic6
ArmorTunic9
CapeOdin
ArmorTunic2
ArmorTunic5
ArmorTunic8
ArmorCarapaceChest
ArmorCarapaceLegs
HelmetCarapace
CapeDeerHide
HelmetDrake
HelmetDraugr0
HelmetDraugr1
HelmetDraugr2
HelmetDraugr3
TrophyDraugrElite
TrophyDraugr
HelmetDverger
HelmetMage
ArmorMageChest
ArmorMageLegs
HelmetHat4
HelmetHat9
CapeFeather
TrophyDraugrFem
HelmetFishingHat
HelmetHat3
HelmetHat8
HelmetOdin
CapeLinen
CapeLox
SaddleLox
BeltStrength
HelmetMidsummerCrown
Krump_Armor_NPC_Chest_01
Krump_Armor_NPC_Chest_02
Krump_Armor_NPC_Chest_03
Krump_Armor_NPC_Helmet_02
Krump_Armor_NPC_Helmet_03
Krump_Armor_NPC_Helmet_04
Krump_Armor_NPC_Helmet_05
DraugrKing_Mace_2Hand
HelmetPadded
HelmetPointyHat
Krump_Armor_Druid_Chest_03
Krump_Armor_Druid_Chest_02
Krump_Armor_Druid_Chest_01
ArmorDress5
ArmorDress2
ArmorDress8
HelmetHat10
HelmetHat5
ArmorDress4
ArmorDress1
ArmorDress10
ArmorDress7
ArmorTunic1
ArmorTunic10
ArmorTunic4
ArmorTunic7
HelmetHat1
HelmetHat6
CapeTrollHide
TrophyFrostTroll
HelmetHat2
HelmetHat7
Demister
ArmorWolfChest
ArmorWolfLegs
CapeWolf
HelmetYule

ArmorBronzeChest
ArmorBronzeLegs
ArmorFenringChest
ArmorFenringLegs
ArmorIronChest
ArmorIronLegs
ArmorLeatherChest
ArmorLeatherLegs
ArmorPaddedCuirass
ArmorPaddedGreaves
ArmorRagsChest
ArmorRagsLegs
ArmorRootChest
ArmorRootLegs
ArmorTrollLeatherChest
ArmorTrollLeatherLegs
AtgeirBlackmetal
AtgeirBronze
AtgeirIron
AxeBlackMetal
AxeBronze
AxeFlint
AxeIron
AxeStone
BarleyWine
Battleaxe
BattleaxeCrystal
BlackSoup
BloodPudding
Blueberries
BoarJerky
Bow
BowDraugrFang
BowFineWood
BowHuntsman
Bread
Carrot
CarrotSoup
Cloudberry
CookedBugMeat
CookedChickenMeat
CookedDeerMeat
CookedEgg
CookedHareMeat
CookedLoxMeat
CookedMeat
CookedWolfMeat
DeerStew
Eyescream
FishAndBread
FishCooked
FishingRod
FishWraps
FistFenrirClaw
HelmetBronze
HelmetFenring
HelmetIron
HelmetLeather
HelmetRoot
HelmetTrollLeather
HoneyGlazedChicken
KnifeBlackMetal
KnifeButcher
KnifeChitin
KnifeCopper
KnifeFlint
KnifeSilver
LoxPie
MaceBronze
MaceIron
MaceSilver
MagicallyStuffedShroom
MeadEitrMinor
MeadFrostResist
MeadHealthMajor
MeadHealthMedium
MeadHealthMinor
MeadPoisonResist
MeadStaminaLingering
MeadStaminaMedium
MeadStaminaMinor
MeadTasty
MeatPlatter
MinceMeatSauce
MisthareSupreme
Mushroom
MushroomBlue
MushroomJotunPuffs
MushroomMagecap
MushroomOmelette
MushroomYellow
NeckTailGrilled
Onion
OnionSoup
PickaxeAntler
QueensJam
Raspberry
RottenMeat
RoyalJelly
Salad
Sausages
SeekerAspic
SerpentMeatCooked
SerpentStew
ShieldBanded
ShieldBlackmetal
ShieldBlackmetalTower
ShieldBoneTower
ShieldBronzeBuckler
ShieldIronBuckler
ShieldIronSquare
ShieldIronTower
ShieldKnight
ShieldSerpentscale
ShieldSilver
ShieldWood
ShocklateSmoothie
SledgeCheat
SledgeIron
SledgeStagbreaker
SpearBronze
SpearChitin
SpearFlint
SpearWolfFang
SwordBlackmetal
SwordBronze
SwordIronFire
SwordSilver
Turnip
TurnipStew
WolfJerky
WolfMeatSkewer
YggdrasilPorridge
ct_campfireinabottle
ct_bonfireinabottle
ct_livingroominabottle

Acorn
Barley
BarleyFlour
BarleyWineBase
Bilebag
BeechSeeds
BirchSeeds
BlackCore
BlackMarble
BlackMetal
BlackMetalScrap
BoneFragments
BreadDough
Bronze
BronzeNails
BronzeScrap
BugMeat
Carapace
CarrotSeeds
ChickenMeat
Chitin
Coal
Copper
CopperOre
CopperScrap
Crystal
Dandelion
DeerHide
DeerMeat
DragonTear
DvergrKeyFragment
DvergrNeedle
Eitr
ElderBark
Entrails
Feathers
FineWood
FirCone
FireworksRocket_Blue
FireworksRocket_Cyan
FireworksRocket_Green
FireworksRocket_Purple
FireworksRocket_Red
FireworksRocket_White
FireworksRocket_Yellow
FishAndBreadUncooked
FishAnglerRaw
FishRaw
Flametal
FlametalOre
Flax
Flint
FreezeGland
GiantBloodSack
Guck
HardAntler
HareMeat
Honey
HoneyGlazedChickenUncooked
Iron
IronNails
Ironpit
IronScrap
JuteBlue
JuteRed
Larva
LeatherScraps
LinenThread
LoxMeat
LoxPieUncooked
MagicallyStuffedShroomUncooked
Mandible
MeadBaseEitrMinor
MeadBaseFrostResist
MeadBaseHealthMajor
MeadBaseHealthMedium
MeadBaseHealthMinor
MeadBasePoisonResist
MeadBaseStaminaLingering
MeadBaseStaminaMedium
MeadBaseStaminaMinor
MeadBaseTasty
MeatPlatterUncooked
MechanicalSpring
MisthareSupremeUncooked
NeckTail
Needle
Obsidian
OnionSeeds
PineCone
QueenDrop
RawMeat
Resin
Root
RoundLog
Sap
ScaleHide
SerpentScale
SharpeningStone
Silver
SilverOre
Softtissue
Stone
Tar
Thistle
Thunderstone
Tin
TinOre
Torch
TrollHide
TurnipSeeds
Wisp
WolfClaw
WolfFang
WolfHairBundle
WolfMeat
WolfPelt
YagluthDrop
YggdrasilWood
YmirRemains
chest_hildir1
chest_hildir2
chest_hildir3
ChickenEgg
CryptKey
DvergrKey
HildirKey_forestcrypt
HildirKey_mountaincave
HildirKey_plainsfortress

Skeleton_Hildir
Skeleton_Hildir_nochest
Fenring_Cultist_Hildir
Fenring_Cultist_Hildir_nochest
GoblinBrute_Hildir
GoblinBruteBros
GoblinBruteBros_nochest
GoblinShaman_Hildir
GoblinShaman_Hildir_nochest


Bat
Blob
Boar
Boar_piggy
Chicken
Leech_cave
Deer
Draugr
Draugr_Elite
Draugr_Ranged
Fenring
DvergerMage
Dverger
DvergerMageFire
DvergerMageIce
DvergerMageSupport
Goblin
GoblinArcher
GoblinBrute
GoblinShaman
Ghost
Neck
Krump_Monster_Neck
Krump_Monster_Neck_Brute
Gjall
Greydwarf
Greydwarf_Elite
Greydwarf_Shaman
Greyling
Hare
Hen
Mistile
TentaRoot
BlobElite
Seeker
SeekerBrood
SeekerBrute
Skeleton
Skeleton_NoArcher
Skeleton_Poison
Skeleton_Friendly
Surtling
SeekerQueen
Tick
Troll
Ulv
Krump_Monsters_NPC_Male0
Krump_Monsters_NPC_Male1
Krump_Monsters_NPC_Male2
Krump_Monsters_NPC_Male3
Krump_Monsters_NPC_Male4
Krump_Monsters_NPC_Random
Player
TheHive
TrainingDummy
Hive

Krump_Tree_Beech_01_Random_Ivy
darkwood_wolf
darkwood_raven
wood_dragon1
piece_chest_treasure
wood_fine_stack
wood_stack
stone_pile
blackmarble_pile
wood_core_stack
wood_yggdrasil_stack
coal_pile
piece_sharpstakes
piece_trap_troll
stake_wall
fuling_turret
piece_dvergr_stake_wall
piece_dvergr_sharpstakes
Karve
Raft
VikingShip
Cart
piece_cartographytable

kg_EnchantmentScrollStation
forge_ext5
piece_workbench_ext4
forge_ext2
cauldron_ext1_spice
piece_oven
cauldron_ext4_pots
forge_ext3
forge_ext4
forge_ext6
piece_cookingstation_iron
piece_cookingstation
piece_cauldron
incinerator
piece_artisanstation
piece_magetable
piece_stonecutter
charcoal_kiln
piece_spinningwheel
forge
fermenter
eitrrefinery
blackforge
blastfurnace
smelter
windmill
forge_ext1
piece_workbench_ext3
piece_magetable_ext2
blackforge_ext1
piece_workbench_ext2
blackforge_ext2_vise
piece_magetable_ext
piece_wisplure
piece_workbench_ext1
piece_sapcollector
piece_beehive
cauldron_ext5_mortarandpestle
cauldron_ext3_butchertable

wood_wall_roof_top
wood_wall_roof_top_45
wood_wall_log_4x0.5
iron_floor_2x2
iron_floor_1x1
stone_wall_2x1
iron_wall_1x1_rusty
wood_wall_log
iron_wall_2x2
woodwall
piece_dvergr_metal_wall_2x2
dvergrprops_wood_stair
piece_dvergr_spiralstair
piece_dvergr_spiralstair_right
wood_stepladder
stone_wall_4x2
stone_floor_2x2
blackmarble_floor_large
stone_floor
piece_dvergr_wood_wall
darkwood_beam_26
woodiron_beam_26
woodiron_pole
wood_beam
darkwood_arch
wood_pole
darkwood_beam4x4
wood_log_45
darkwood_pole4
wood_beam_1
wood_ledge
wood_pole2
wood_beam_45
wood_beam_26
darkwood_decowall
wood_log_26
woodiron_beam_45
piece_dvergr_pole
darkwood_beam
woodiron_beam
darkwood_pole
darkwood_beam_45
wood_wall_quarter
wood_wall_half
wood_window
crystal_wall_1x1
darkwood_gate
piece_dvergr_wood_door
iron_grate
wood_door
piece_hexagonal_door
wood_gate
wood_pole_log
wood_pole_log_4
darkwood_roof_45
OLD_wood_roof_icorner
wood_roof_icorner_45
darkwood_roof_ocorner
wood_roof_ocorner_45
wood_roof
darkwood_roof
darkwood_roof_ocorner_45
darkwood_roof_icorner_45
wood_roof_45
wood_roof_ocorner
turf_roof
darkwood_roof_icorner
OLD_wood_roof_ocorner
wood_roof_icorner
wood_floor_1x1
wood_floor
stone_arch
wood_wall_roof_45
wood_wall_roof_upsidedown
wood_wall_roof_45_upsidedown
OLD_wood_wall_roof
wood_wall_roof
blackmarble_creep_stair
stone_stair
blackmarble_stair_corner_left
blackmarble_stair_corner
wood_roof_top_45
wood_roof_top
darkwood_roof_top
turf_roof_top
darkwood_roof_top_45
blackmarble_base_1
blackmarble_arch
blackmarble_2x2_enforced
metalbar_1x2
blackmarble_head01
blackmarble_base_2
blackmarble_2x2x2
blackmarble_out_2 
blackmarble_tile_wall_1x1
blackmarble_tile_floor_1x1
blackmarble_tile_floor_2x2
blackmarble_creep_4x2x1
blackmarble_slope_inverted_1x2
blackmarble_outcorner
blackmarble_out_1
blackmarble_tip
blackmarble_tile_wall_2x4
blackmarble_head_big01
blackmarble_head_big02
blackmarble_basecorner
blackmarble_column_2
blackmarble_2x1x1
stone_wall_1x1
blackmarble_floor
blackmarble_floor_triangle
blackmarble_column_3
blackmarble_tile_wall_2x2
blackmarble_head02
blackmarble_column_1
blackmarble_slope_1x2
stone_pillar








