# List out items prefabs to ignore:

StaminaUpgrade_Greydwarf
StaminaUpgrade_Troll
StaminaUpgrade_Wraith
IronOre
DvergerArbalest_shoot
DvergerArbalest
CapeTest
SledgeCheat
SwordCheat
HealthUpgrade_Bonemass
HealthUpgrade_GDKing
guard_stone_test
Trailership
TorchMist
NPC_HelmetIron_Worn0
NPC_HelmetBronze_Worn0
NPC_ArmorIronChest_Worn
NPC_ArmorIronLegs_Worn
VegvisirShard_Bonemass
Cat1_Kitten
Cat2_Kitten
Cat3_Kitten
Cat4_Kitten
Cat5_Kitten
Cat6_Kitten
Cat7_Kitten
Cat8_Kitten
Cat9_Kitten
Cat10_Kitten
Cat11_Kitten
KittenHappyBox

Player
TentaRoot
TheHive
TrainingDummy
Hive
Mistile
Boar
Boar_piggy
Chicken
Deer
Greyling
Troll
Greydwarf
Greydwarf_Elite
Greydwarf_Shaman
Draugr
Draugr_Elite
Draugr_Ranged
Blob
BlobElite

ArmorBronzeChest
ArmorBronzeLegs
ArmorFenringChest
ArmorFenringLegs
ArmorIronChest
ArmorIronLegs
ArmorLeatherChest
ArmorLeatherLegs
ArmorPaddedCuirass
ArmorPaddedGreaves
ArmorRagsChest
ArmorRagsLegs
ArmorRootChest
ArmorRootLegs
ArmorTrollLeatherChest
ArmorTrollLeatherLegs
AtgeirBlackmetal
AtgeirBronze
AtgeirIron
AxeBlackMetal
AxeBronze
AxeFlint
AxeIron
AxeStone
Battleaxe
BattleaxeCrystal
Bow
BowDraugrFang
BowFineWood
BowHuntsman
FishingRod
FistFenrirClaw
HelmetBronze
HelmetFenring
HelmetIron
HelmetLeather
HelmetRoot
HelmetTrollLeather
KnifeBlackMetal
KnifeButcher
KnifeChitin
KnifeCopper
KnifeFlint
KnifeSilver
MaceBronze
MaceIron
MaceSilver
PickaxeAntler
ShieldBanded
ShieldBlackmetal
ShieldBlackmetalTower
ShieldBoneTower
ShieldBronzeBuckler
ShieldIronBuckler
ShieldIronSquare
ShieldIronTower
ShieldKnight
ShieldSerpentscale
ShieldSilver
ShieldWood
SledgeCheat
SledgeIron
SledgeStagbreaker
SpearBronze
SpearChitin
SpearFlint
SpearWolfFang
SwordBlackmetal
SwordBronze
SwordIronFire
SwordSilver

Krump_Vanilla_Replaced
